CREATE TABLE attendance_records (
 id uuid PRIMARY KEY DEFAULT uuidv7(), organization_id uuid NOT NULL REFERENCES organizations(id), employee_id uuid NOT NULL, work_date date NOT NULL, schedule_assignment_id uuid, schedule_version_id uuid,
 first_in timestamptz, last_out timestamptz, worked_minutes integer NOT NULL DEFAULT 0 CHECK(worked_minutes>=0), late_minutes integer NOT NULL DEFAULT 0 CHECK(late_minutes>=0), undertime_minutes integer NOT NULL DEFAULT 0 CHECK(undertime_minutes>=0), attendance_status text NOT NULL CHECK(attendance_status IN ('present','late','absent','on_leave','rest_day','incomplete')), approval_status text NOT NULL DEFAULT 'unreviewed' CHECK(approval_status IN ('unreviewed','approved','needs_review')),
 input_hash text NOT NULL, result jsonb NOT NULL, approved_by uuid REFERENCES auth_users(id), approved_at timestamptz, revision integer NOT NULL DEFAULT 1 CHECK(revision>0), updated_by uuid REFERENCES auth_users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,employee_id,work_date), UNIQUE(organization_id,id), FOREIGN KEY(organization_id,employee_id) REFERENCES employees(organization_id,id), FOREIGN KEY(organization_id,schedule_assignment_id) REFERENCES employee_schedule_assignments(organization_id,id), FOREIGN KEY(organization_id,schedule_version_id) REFERENCES work_schedule_versions(organization_id,id)
);
CREATE INDEX attendance_date_idx ON attendance_records(organization_id,work_date,attendance_status);
CREATE TABLE attendance_history (id uuid PRIMARY KEY DEFAULT uuidv7(), organization_id uuid NOT NULL REFERENCES organizations(id), attendance_id uuid NOT NULL, revision integer NOT NULL, snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(organization_id,attendance_id) REFERENCES attendance_records(organization_id,id), UNIQUE(attendance_id,revision));
CREATE TABLE attendance_adjustments (id uuid PRIMARY KEY DEFAULT uuidv7(), organization_id uuid NOT NULL REFERENCES organizations(id), attendance_id uuid NOT NULL, overrides jsonb NOT NULL, reason text NOT NULL CHECK(length(btrim(reason))>0), revision integer NOT NULL CHECK(revision>0), created_by uuid NOT NULL REFERENCES auth_users(id), created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(organization_id,attendance_id) REFERENCES attendance_records(organization_id,id), UNIQUE(attendance_id,revision));
CREATE TABLE attendance_processing_jobs (id uuid PRIMARY KEY DEFAULT uuidv7(), organization_id uuid NOT NULL REFERENCES organizations(id), employee_id uuid NOT NULL, start_date date NOT NULL, end_date date NOT NULL CHECK(end_date>=start_date), next_date date NOT NULL, requested_by uuid NOT NULL REFERENCES auth_users(id), created_at timestamptz NOT NULL DEFAULT now(), last_error text, FOREIGN KEY(organization_id,employee_id) REFERENCES employees(organization_id,id));
CREATE INDEX attendance_jobs_pending_idx ON attendance_processing_jobs(created_at);
CREATE TABLE attendance_processing_cursors (organization_id uuid PRIMARY KEY REFERENCES organizations(id), next_date date NOT NULL);
REVOKE UPDATE,DELETE,TRUNCATE ON attendance_history,attendance_adjustments FROM hexpayroll_app;
