import { z } from 'zod';

/**
 * Validation primitives shared by the API (inbound request validation) and the
 * web/desktop clients (form validation), so a rule is written once.
 *
 * Only long-stable Zod APIs are used here on purpose: these schemas sit on the
 * boundary of every request, so they should not depend on recently-renamed or
 * deprecated helpers.
 */

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/** A UUID primary key. Payroll rows use `uuidv7()` generated by PostgreSQL 18. */
export const uuidSchema = z.string().regex(UUID_PATTERN, 'must be a UUID');

/** A safe integer number of centavos. See `money.ts` — money is never a float. */
export const centavosSchema = z
  .number()
  .refine(Number.isSafeInteger, 'must be a whole number of centavos');

/** A calendar date with no time component, e.g. "2026-09-28". */
export const isoDateSchema = z.string().regex(ISO_DATE_PATTERN, 'must be an ISO date (YYYY-MM-DD)');

/** A string that must contain at least one non-whitespace character. */
export const nonEmptyTrimmedString = z.string().trim().min(1);

/** Non-negative centavos — for amounts that can never go below zero. */
export const nonNegativeCentavosSchema = centavosSchema.refine(
  (value) => value >= 0,
  'must not be negative',
);

export type Uuid = z.infer<typeof uuidSchema>;
export type IsoDate = z.infer<typeof isoDateSchema>;
